### ISSUE TITLE
Release for melodic

### ISSUE THREAD

**Issue by paulbovbel** [locusrobotics/aiorospy#15]
This requires figuring out how to handle the python3.7 dependency.

We can swap asyncio.create_task for ensure_future, and drop back down to 3.6

We also need to use the new package.xml conditional dependency feature to put `python3.x` behind a flag that's ignored on ROS buildfarm.

**Comment by ablakey** [comment]
I originally had 3.6 targeted (see README) but I must have inadvertently added 3.7 dependencies.

That last requirement sounds like a big one.

**Comment by paulbovbel** [comment]
I bumped it to 3.7 because of the plethora of create_task

The last one's not too bad, I need to update our internal CI to use the latest python3-rosdistro versions so these conditional features are supported.

**Comment by ablakey** [comment]
Oh the conditional feature exists already. We just have to update to support it. Gotcha.
