### ISSUE TITLE
Failed to setup package

### ISSUE THREAD

**Issue by peetCreative** [locusrobotics/aiorospy#41]
Hey,
I wondered how to setup this package (and integrate into my package). So I just cloned it to a fresh catkin_ws/src. 
Well there's the [issue](https://github.com/locusrobotics/catkin_virtualenv/issues/83) from catkin_virtualenv (I already installed it for another package) up.
`add_custom_target cannot create target "venv_lock" because another target with the same name already exists`
So for the first I removed aiorospy_examples. This resolved this issue for the first. Eventhough I cannot use catkin_virtualenv in my own project now...

Going further, I now run into the following error:
`No rule to make target  ...catkin_ws/src/requirements.in`
Which looks odd.

Someone ideas with this? Or can maybe give a setup tutorial?

**Comment by garyservin** [comment]
Hey Peter, 

for your second issue, you need to create the `requirements.in` file specifying all of your pip dependencies, similarly to a `requirements.txt`

**Comment by peetCreative** [comment]
Towards your suggestion I'm not sure what you mean. I expected the standalone package  to compile and be able to run out of the box using `catkin_make` and `rosrun aiorospy_example ....`.

However I think I found [this closed issue](https://github.com/locusrobotics/catkin_virtualenv/issues/25), which basically says:
`catkin_virtualenv` is not compatible with `catkin_make`, because every virtual_env must be generated on it's own. So one should rather use `catkin_make_isolated`.

**Comment by Ed562** [comment]
> Towards your suggestion I'm not sure what you mean. I expected the standalone package to compile and be able to run out of the box using `catkin_make` and `rosrun aiorospy_example ....`.
> 
> However I think I found [this closed issue](https://github.com/locusrobotics/catkin_virtualenv/issues/25), which basically says: `catkin_virtualenv` is not compatible with `catkin_make`, because every virtual_env must be generated on it's own. So one should rather use `catkin_make_isolated`.

catkin_make_isolated did it for me. Thanks!
